# Generated by Django 4.0.7 on 2023-06-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Dietaries',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('audiences', models.ManyToManyField(related_name='email', to='weddingwrangle.audience')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RSVPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=50)),
                ('rsvp_link', models.CharField(max_length=15)),
                ('rsvp_qr', models.BinaryField(blank=True, editable=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audiences', models.ManyToManyField(related_name='guest', to='weddingwrangle.audience')),
                ('dietaries', models.ManyToManyField(related_name='guest', to='weddingwrangle.dietary')),
                ('emails', models.ManyToManyField(related_name='guest', to='weddingwrangle.email')),
                ('partnership', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_guest', to='weddingwrangle.rsvpstatus')),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='weddingwrangle.position')),
                ('rsvp_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='weddingwrangle.rsvpstatus')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='weddingwrangle.title')),
            ],
        ),
    ]
