# Generated by Django 4.0.7 on 2023-06-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Dietaries (Other)',
            },
        ),
        migrations.AlterModelOptions(
            name='rsvpstatus',
            options={'verbose_name': 'RSVP Status', 'verbose_name_plural': 'RSVP Statuses'},
        ),
        migrations.AlterField(
            model_name='rsvpstatus',
            name='name',
            field=models.CharField(max_length=11),
        ),
    ]
