# Generated by Django 4.0.7 on 2023-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0002_dietaryother_alter_rsvpstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_link',
            field=models.CharField(max_length=15, verbose_name='RSVP Link'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_qr',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='RSVP QR'),
        ),
    ]
