# Generated by Django 4.0.7 on 2023-06-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0003_alter_guest_rsvp_link_alter_guest_rsvp_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='partnership',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='weddingwrangle.partnership'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='weddingwrangle.rsvpstatus', verbose_name='RSVP Status'),
        ),
    ]
