# Generated by Django 4.0.7 on 2023-06-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0004_alter_guest_partnership_alter_guest_rsvp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='weddingwrangle.partnership'),
        ),
    ]
