# Generated by Django 4.0.7 on 2023-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0008_alter_guest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpstatus',
            name='verbose_name',
            field=models.CharField(default='I am delighted to accept', max_length=50),
            preserve_default=False,
        ),
    ]
