# Generated by Django 4.0.7 on 2023-07-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0009_rsvpstatus_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='partnership',
        ),
        migrations.AddField(
            model_name='guest',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddingwrangle.guest'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Partnership',
        ),
    ]
