# Generated by Django 4.0.7 on 2023-07-05 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0010_remove_guest_partnership_guest_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
