# Generated by Django 4.0.7 on 2023-07-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0013_email_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='audience', to='weddingwrangle.position'),
        ),
        migrations.AddField(
            model_name='audience',
            name='rsvp_statuses',
            field=models.ManyToManyField(blank=True, related_name='audience', to='weddingwrangle.rsvpstatus'),
        ),
    ]
