# Generated by Django 4.0.7 on 2023-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0014_audience_positions_audience_rsvp_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
