# Generated by Django 4.0.7 on 2023-07-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0017_alter_email_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_qr',
            field=models.BinaryField(blank=True, null=True, verbose_name='RSVP QR'),
        ),
    ]
