# Generated by Django 4.0.7 on 2023-07-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0018_alter_guest_rsvp_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='sent',
        ),
    ]
