# Generated by Django 4.0.7 on 2023-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0005_alter_guest_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietaries',
            field=models.ManyToManyField(blank=True, related_name='guest', to='weddingwrangle.dietary'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='guest', to='weddingwrangle.email'),
        ),
    ]
