# Generated by Django 4.0.7 on 2023-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0006_alter_guest_dietaries_alter_guest_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='guest', to='weddingwrangle.audience'),
        ),
    ]
