# Generated by Django 4.0.7 on 2023-06-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0007_alter_guest_audiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='weddingwrangle.position'),
        ),
    ]
