# Generated by Django 4.0.7 on 2023-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0011_guest_rsvp_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
