# Generated by Django 4.0.7 on 2023-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingwrangle', '0016_remove_email_audiences_email_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.CharField(default='', max_length=10000000),
            preserve_default=False,
        ),
    ]
