# Generated by Django 4.2.7 on 2025-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weddingwrangle", "0023_alter_email_audience"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DietaryOther",
        ),
        migrations.AddField(
            model_name="guest",
            name="dietary_other",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
